# Generated by Django 2.2.10 on 2020-05-05 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('read_statistics', '0003_auto_20200420_2110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='readdetail',
            options={'verbose_name': '阅读记录', 'verbose_name_plural': '阅读记录'},
        ),
        migrations.AlterModelOptions(
            name='readnum',
            options={'verbose_name': '阅读数', 'verbose_name_plural': '阅读数'},
        ),
    ]
