# Generated by Django 2.2.10 on 2020-05-05 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestbook',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='guestbook',
            name='object_id',
        ),
        migrations.AlterField(
            model_name='guestbook',
            name='content',
            field=models.TextField(verbose_name='留言内容'),
        ),
        migrations.AlterField(
            model_name='guestbook',
            name='message_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='留言时间'),
        ),
        migrations.AlterField(
            model_name='guestbook',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guestbook', to=settings.AUTH_USER_MODEL, verbose_name='留言者'),
        ),
    ]
