# Generated by Django 2.2.10 on 2020-04-04 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200404_1436'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
